# Generated by Django 4.0.3 on 2023-04-10 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEstable', models.CharField(max_length=50)),
                ('descripcion_Estable', models.CharField(max_length=250)),
                ('sitio_web', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, default='------', max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('correo_tienda', models.CharField(blank=True, max_length=200, null=True)),
                ('latitud', models.CharField(max_length=25)),
                ('longitud', models.CharField(max_length=25)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=10, null=True)),
                ('imagen', models.ImageField(upload_to='perfiles')),
                ('lunes_entrada', models.CharField(blank=True, max_length=10, null=True)),
                ('lunes_salida', models.CharField(blank=True, max_length=10, null=True)),
                ('every_allday', models.CharField(blank=True, max_length=2, null=True)),
                ('martes_entrada', models.CharField(blank=True, max_length=10, null=True)),
                ('martes_salida', models.CharField(blank=True, max_length=10, null=True)),
                ('miercoles_entrada', models.CharField(blank=True, max_length=10, null=True)),
                ('miercoles_salida', models.CharField(blank=True, max_length=10, null=True)),
                ('jueves_entrada', models.CharField(blank=True, max_length=10, null=True)),
                ('jueves_salida', models.CharField(blank=True, max_length=10, null=True)),
                ('viernes_entrada', models.CharField(blank=True, max_length=10, null=True)),
                ('viernes_salida', models.CharField(blank=True, max_length=10, null=True)),
                ('sabado_entrada', models.CharField(blank=True, max_length=10, null=True)),
                ('sabado_salida', models.CharField(blank=True, max_length=10, null=True)),
                ('domingo_entrada', models.CharField(blank=True, max_length=10, null=True)),
                ('domingo_salida', models.CharField(blank=True, max_length=10, null=True)),
                ('validate', models.BooleanField(default=False)),
                ('recomendado', models.BooleanField(default=False)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('recomendado2', models.BooleanField(default=False)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfil.categoria')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to=settings.AUTH_USER_MODEL)),
                ('vistos', models.ManyToManyField(blank=True, related_name='visitados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resenias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('validate', models.BooleanField(default=False)),
                ('estrellas', models.IntegerField(default=0)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_resenia', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('validate', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='publicaciones')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_post', to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('validate', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_comentario', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='perfil.comentario')),
            ],
        ),
    ]
