# Generated by Django 4.0.3 on 2023-04-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen_predeterminada', models.ImageField(default='productos/consultb.jpeg', upload_to='productos')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='perfil.perfil')),
            ],
        ),
    ]
