# Generated by Django 4.0.3 on 2023-04-11 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='perfil',
        ),
        migrations.AddField(
            model_name='perfil',
            name='productos',
            field=models.ManyToManyField(blank=True, to='perfil.producto'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='perfil.perfil'),
        ),
    ]
