# Generated by Django 4.0.3 on 2023-04-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_remove_producto_perfil_perfil_productos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen_predeterminada', models.ImageField(default='productos/consultb.jpeg', upload_to='productos')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('create', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_predeterminada',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
