# Generated by Django 4.0.3 on 2023-04-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_articulo_remove_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulo',
        ),
    ]
