# Generated by Django 4.0.3 on 2023-04-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_delete_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagen_predeterminada', models.ImageField(default='articulos/consultb.jpeg', upload_to='articulos')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos')),
                ('create', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
