# Generated by Django 4.0.3 on 2023-04-12 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil'),
            preserve_default=False,
        ),
    ]
