# Generated by Django 4.0.3 on 2023-04-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_articulo_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='perfil.perfil'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
