# Generated by Django 4.0.3 on 2023-04-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_alter_perfil_correo_tienda_alter_perfil_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='colonia',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
