# Generated by Django 4.0.3 on 2023-04-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0011_perfil_colonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagen_predeterminada',
            field=models.ImageField(default='perfiles/shop.png', upload_to='perfiles'),
        ),
    ]
