# Generated by Django 4.0.3 on 2023-04-13 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0013_alter_perfil_colonia_alter_perfil_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='creat',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
